spring:
  datasource:
    #表明使用Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.112.14.207:8001/dimple_blog?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    #初始时建立物理连接的个数
    initial-size: 10
    #最小链接池数量
    min-idle: 10
    #最大连接池数量
    max-active: 40
    #获取链接等待超时时间，单位毫秒
    max-wait: 60000
    #间隔多久进行一次检测，关闭需要关闭的链接
    time-between-eviction-runs-millis: 60000
    #一个连接在连接池中最小生存的时间
    min-evictable-idle-time-millis: 30000
    #一个链接在连接池中最大生存的时间
#    max-evictable-idle-time-millis: 90000
    ##是否缓存preparedStatement，也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
    pool-prepared-statements: false
    #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    max-open-prepared-statements: -1
    username: dimple
    password: 123456
    validationQuery: SELECT 1 FROM DUAL
    druid:
      clear-filters-enable: true
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true