version : '3.9'
services:
  dimple-nacos:
    container_name: dimple-nacos
    image: nacos/nacos-server
    hostname: dimple-nacos
    build:
      context: ./nacos
    environment:
      - MODE=standalone
      - JVM_XMS=512m
      - JVM_XMX=512m
      - JVM_XMN=128m
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - dimple-mysql
  dimple-mysql:
    container_name: dimple-mysql
    image: mysql
    hostname: dimple-mysql
    build:
      context: ./mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=80M',
      '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'dimple-cloud'
      MYSQL_ROOT_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 512M
  dimple-redis:
    container_name: dimple-redis
    image: redis
    hostname: dimple-redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/dimple/redis/redis.conf
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: redis-server /home/dimple/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 512M
  dimple-ui:
    container_name: dimple-ui
    image: nginx
    privileged: true
    build:
      context: nginx
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx-blog/admin/dist/:/home/dimple/projects/dimple-ui-admin/
      - ./nginx-blog/blog/dist/:/home/dimple/projects/dimple-ui-blog/
      - ./nginx-blog/conf/nginx.conf:/etc/nginx/dimple-ui-blog/nginx.conf
      - ./nginx-blog/logs:/var/log/dimple-ui-blog/nginx
      - ./nginx-blog/conf.d:/etc/nginx/dimple-ui-blog/conf.d
    depends_on:
      - dimple-gateway
    links:
      - dimple-gateway
    deploy:
      resources:
        limits:
          memory: 256M
  dimple-gateway:
    container_name: dimple-gateway
    build:
      context: ./dimple/gateway/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dimple-redis
    links:
      - dimple-redis
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-auth:
    container_name: dimple-auth
    build:
      context: ./dimple/auth/
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - dimple-redis
    links:
      - dimple-redis
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-system:
    container_name: dimple-modules-system
    build:
      context: ./dimple/modules/system/
      dockerfile: Dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - dimple-redis
      - dimple-mysql
    links:
      - dimple-redis
      - dimple-mysql
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-job:
    container_name: dimple-modules-job
    build:
      context: ./dimple/modules/job/
      dockerfile: Dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - dimple-mysql
    links:
      - dimple-mysql
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-file:
    container_name: dimple-modules-file
    build:
      context: ./dimple/modules/file/
      dockerfile: Dockerfile
    ports:
      - "9300:9300"
    volumes:
      - ./file/uploadPath:/home/dimple/uploadPath
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-monitor:
    container_name: dimple-modules-monitor
    build:
      context: ./dimple/modules/monitor/
      dockerfile: Dockerfile
    ports:
      - "9100:9100"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-blog:
    container_name: dimple-modules-blog
    build:
      context: ./dimple/modules/blog/
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9401:9401"
    depends_on:
      - dimple-redis
      - dimple-mysql
    links:
      - dimple-redis
      - dimple-mysql
  dimple-modules-blog-front:
    container_name: dimple-modules-blog-front
    build:
      context: ./dimple/modules/blog-front/
      dockerfile: Dockerfile
    ports:
      - "9500:9500"
    depends_on:
      - dimple-redis
      - dimple-mysql
    links:
      - dimple-redis
      - dimple-mysql
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
  dimple-modules-log:
    container_name: dimple-modules-log
    build:
      context: ./dimple/modules/log/
      dockerfile: Dockerfile
    ports:
      - "9408:9408"
    depends_on:
      - dimple-redis
      - dimple-mysql
    links:
      - dimple-redis
      - dimple-mysql
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m